### ISSUE TITLE
Thevayattra pathivu

### ISSUE THREAD

**Issue by Sabariji-R-R-V** [minionibrahim/SamplePage#4]
Dont write unwanted messages in my Code
If u still doing im taking to legal steps

**Comment by minionibrahim** [comment]
do what you can...

**Comment by minionibrahim** [comment]
https://developer.android.com/studio?gclid=Cj0KCQjw9YWDBhDyARIsADt6sGYC8mV0vXlqQkiwy0b2oa9CJYL4aM-O6qzaPWD38WRtCnbAN8EBc2EaAunLEALw_wcB&gclsrc=aw.ds
